---
title: "INF2178_Week3_Note"
author: "Renjing Liu"
date: "2021/2/2"
output: html_document
---
read.csv("my_data.csv")
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#?runif
my_data<- runif(n= 10, min=0, max = 50)
hist(my_data)
sort(my_data)
write.csv(my_data, file="my_data.csv")

more_data<- rnorm()
```

```{r}
library(tidyverse)

set.seed(123)
population<-
  tibble(person= c(1:10000),
         favourite_color = sample(x= c("Black","White"),
                                  size = 10000,
                                  prob = c(0.25,0.75),
                                  replace = TRUE),
         supports_the_leafs = sample(x=c("yes","no"),
                                     size= 10000,
                                     replace = TRUE,
                                     prob = c(0.8,0.2)) %>%
           mutate(in_frame = sample(x=c(0:1),
                                    size = 10000,
                                    replace = TRUE))%>%
           mutate(group= sample(x=c(0:1),
                                size= 10000,
                                replace = TRUE))%>%
           mutate(group= ifelse(in_frame==1, group, NA))
           
         )
    
  )
```